<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Troubleshooting on Blog - uTIcARdI</title><link>https://blog.gainskills.top/tags/troubleshooting/</link><description>Recent content in Troubleshooting on Blog - uTIcARdI</description><generator>Hugo -- gohugo.io</generator><language>en-us</language><lastBuildDate>Fri, 01 Mar 2019 00:00:00 +0000</lastBuildDate><atom:link href="https://blog.gainskills.top/tags/troubleshooting/index.xml" rel="self" type="application/rss+xml"/><item><title>File name on windows</title><link>https://blog.gainskills.top/2019/03/01/file-name-on-winos/</link><pubDate>Fri, 01 Mar 2019 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2019/03/01/file-name-on-winos/</guid><description>Error 1 Run a bat (ping.bat) to ping multiple IPs like this: set testipa=x.x.x.x echo Checking ping %testipa% (15 times), please don&amp;#39;t close current window echo ping %testipa% (15 times) &amp;gt;&amp;gt; test.log ping %testipa% -w 500 -n 15 &amp;gt;&amp;gt; test.log
But got the following error: Checking ping x.x.x.x (15 times), please don&amp;#39;t close current window The process cannot access the file because it is being used by another process. The process cannot access the file because it is being used by another process.</description></item><item><title>aiohttp/aiodns-Resolving using custom nameservers</title><link>https://blog.gainskills.top/2019/01/23/try-aiohttp/</link><pubDate>Wed, 23 Jan 2019 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2019/01/23/try-aiohttp/</guid><description>aiohttp is an Asynchronous HTTP client/server framework for asyncio and Python
I tried it because of the features:
Tuning the DNS cache Resolving using custom nameservers With this, verifying the CDN&amp;rsquo;s POPs with different ISPs&amp;rsquo; DNS on single a point should be possible.
Since the code on the official document is simple:
from aiohttp.resolver import AsyncResolver
resolver = AsyncResolver(nameservers=[&amp;ldquo;8.8.8.8&amp;rdquo;, &amp;ldquo;8.8.4.4&amp;rdquo;]) conn = aiohttp.TCPConnector(resolver=resolver)
I tried it with following code: ~~~python import aiohttp import asyncio from aiohttp.</description></item><item><title>get() in get() method of Pyhon dict</title><link>https://blog.gainskills.top/2019/01/19/get-in-dict-get/</link><pubDate>Wed, 09 Jan 2019 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2019/01/19/get-in-dict-get/</guid><description>Write down the tip for the practice: The Time in Words.
A dict was created for the time in number format to string format:
intToStrDict = { 1: &amp;#39;one&amp;#39;, 2: &amp;#39;two&amp;#39;, 3: &amp;#39;three&amp;#39;, 4: &amp;#39;four&amp;#39;, 5: &amp;#39;five&amp;#39;, 6: &amp;#39;six&amp;#39;, 7: &amp;#39;seven&amp;#39;, 8: &amp;#39;eight&amp;#39;, 9: &amp;#39;nine&amp;#39;, 10: &amp;#39;ten&amp;#39;, 11: &amp;#39;eleven&amp;#39;, 12: &amp;#39;twelve&amp;#39;, 13: &amp;#39;thirteen&amp;#39;, 14: &amp;#39;fourteen&amp;#39;, 15: &amp;#39;quarter&amp;#39;, 16: &amp;#39;sixteen&amp;#39;, 17: &amp;#39;seventeen&amp;#39;, 18: &amp;#39;eighteen&amp;#39;, 19: &amp;#39;nineteen&amp;#39;, 20: &amp;#39;twenty&amp;#39;, 30: &amp;#39;half&amp;#39;, 40: &amp;#39;fourty&amp;#39;, 50: &amp;#39;fifty&amp;#39; } get() is a good way get the value of a key from the dict, so I tried following function to convert minute in number format to string format:</description></item><item><title>AWS S3 Bucket Creation</title><link>https://blog.gainskills.top/2018/12/27/aws-s3-bucket-creation/</link><pubDate>Thu, 27 Dec 2018 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2018/12/27/aws-s3-bucket-creation/</guid><description>Try to create a bucket with the Python library: boto3
from boto3.session import Session session=Session(aws_access_key_id=&amp;#39;key1&amp;#39;, aws_secret_access_key=&amp;#39;key2&amp;#39;) s3 = session.resource(&amp;#39;s3&amp;#39;) s3.create_bucket(Bucket=&amp;#39;kz-testbucket&amp;#39;) but failed to run the script with errors:
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.
botocore.errorfactory.BucketAlreadyExists: An error occurred (BucketAlreadyExists) when calling the CreateBucket operation: The requested bucket name is not available.</description></item><item><title>Jenkins/Xcode plugin for iOS project delivery</title><link>https://blog.gainskills.top/2018/12/18/jenkinsx-iosproject-delivery/</link><pubDate>Tue, 18 Dec 2018 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2018/12/18/jenkinsx-iosproject-delivery/</guid><description>Most of this blog is discuss the errors and how I resolve the errors when I try iOS project Continuous Delivery with Jenkins. The brief steps are:
Install Jenkins
Install Xcode plugin on Jenkins
New a ‘Freestyle project’ on Jenkins
Jenkins project configuration
‘Source Code Management’ on Jenkins ‘Build’ setting on Jenkins Jenkins Project -&amp;gt; ‘Build Now’
Errors:</description></item><item><title>Netconf feature on Cisco IOS/IOSXE</title><link>https://blog.gainskills.top/2018/10/07/netconf-feature-on-cisco-ios-iosxe/</link><pubDate>Sun, 07 Oct 2018 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2018/10/07/netconf-feature-on-cisco-ios-iosxe/</guid><description>I tried to see how Ansible works with the netconf feature on Cisco and Juniper in past days: Juniper’s official document is clear and easy to follow. but for Cisco, I followed NETCONF over SSHv2, unfortunately, I was stuck on it for 6 days. OS Version Cisco IOS XE Software, Version 16.04.01 Cisco IOS Software, Linux Software (I86BI_LINUXL2-IPBASEK9-M), Experimental Version 15.2(20170809:194209) [dstivers-aug9_]</description></item><item><title>Mininet-ImportError: customClass</title><link>https://blog.gainskills.top/2018/07/20/mininet-importerror-customclass/</link><pubDate>Fri, 20 Jul 2018 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2018/07/20/mininet-importerror-customclass/</guid><description>I tried to run miniedit.py after I have mininet installed, unfortunately, I got the error:
ImportError: cannot import name customClass. Error Checked the py file: ~/mininet/mininet/util.py and miniedity.py, find nothing is wrong, search on the Internet, got no clue.
Suddenly I found the version is not the version I wanted to install (I forgot to take a screenshot, the version should be 2.2.2daily something).
I guess there must be something wrong with the latest version, or there is something conflict with my previous version (mininet 2.</description></item><item><title>Flask, Flask-WTF, Flask-Bootstrap, Select2, jinja2 integration</title><link>https://blog.gainskills.top/2018/04/16/flask-flask-wtf-flask-bootstrap-select2-jinja2-integration/</link><pubDate>Mon, 16 Apr 2018 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2018/04/16/flask-flask-wtf-flask-bootstrap-select2-jinja2-integration/</guid><description>I intend to acquire the Python skill on web after years&amp;rsquo; work on data processing, so I started with Flask by the following Miguel Grinberg&amp;rsquo;s instruction: The Flask Mega, you can learn how to integrate bootstrap with your project from it. After that, you can learn how to integrate select2 with your project by reading Flask Web开发:用Select2</description></item><item><title>Python SMTPlib/Email</title><link>https://blog.gainskills.top/2018/02/13/python-smtplib-email/</link><pubDate>Tue, 13 Feb 2018 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2018/02/13/python-smtplib-email/</guid><description>I followed the instruction which is written in Chinese to learn how to send emails by Python, here some tips from my practice:
Name of the attachment is shown as ‘ATT00002’
The name of the attachment in the receiver mailbox is shown in the format ‘ATT0000X‘ with the code:
att1[&amp;#34;Content-Disposition&amp;#34;] = &amp;#39;attachment; filename=&amp;#34;runoob.txt&amp;#34;&amp;#39; Issue The issue can be fixed by using .addheader() function:</description></item><item><title>OverflowError: signed char is greater than maximum</title><link>https://blog.gainskills.top/2017/06/06/overflowerror-signed-char-is-greater-than-maximum/</link><pubDate>Tue, 06 Jun 2017 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2017/06/06/overflowerror-signed-char-is-greater-than-maximum/</guid><description>Here the pseudo code about the flow:
from array import array c = array(&amp;#39;b&amp;#39;) with open(file, mode = &amp;#39;rb&amp;#39;) as f: for character in f: res = func(character) c.append(res) It runs into the error:
OverflowError: signed char is greater than maximum with a special character &amp;lsquo;À&amp;rsquo; which its binary value is 192:
Character My way to resolve this error is to update the type code of the array from &amp;lsquo;b&amp;rsquo; (signed char) to &amp;lsquo;B&amp;rsquo; (unsigned char).</description></item><item><title>Adding Realtek 8139 Driver to ESXi6</title><link>https://blog.gainskills.top/2016/11/29/adding-realtek-8139-driver-to-esxi6/</link><pubDate>Tue, 29 Nov 2016 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2016/11/29/adding-realtek-8139-driver-to-esxi6/</guid><description>Note: This is not an official guide, backup is required before you apply the driver. My Dell PC has two NICs:
Intel I217-LM Realtek RTl-8139 and #2 Realtek 8139 is not supported by VMware EXSi.
There are some guides about customizing EXSi installation ISO to support the NIC, but I’m trying to find a way to apply the driver without reinstall EXSi.
Here is a page which contains many NIC drivers: https://vibsdepot.</description></item><item><title>VSphere6, VCenter6 Installation</title><link>https://blog.gainskills.top/2016/01/08/vsphere6-vcenter6-installation/</link><pubDate>Fri, 08 Jan 2016 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2016/01/08/vsphere6-vcenter6-installation/</guid><description>Crash happened when I install Vsphere on my PC
Solution: Disable option &amp;ldquo;Limit Maximum CPUID&amp;rdquo; in Bios
VCenter appliance deployment
Vmware doesn&amp;rsquo;t provide vcenter appliance in ova/ovf format anymore, follow the instruction to deploy it.
Inventory is empty in the VCenter webpage
The most important thing: Don&amp;rsquo;t login vcenter by the account &amp;lsquo;root&amp;rsquo;, instead of it using SSO account. the account in the format: &amp;lsquo;administrator@domain-name&amp;rsquo;</description></item><item><title>Dynagen/Dynamips error: netio_desc_create_udp: unable to connect to</title><link>https://blog.gainskills.top/2013/12/20/dynagen-dynamips-error-netio_desc-create-udp-unable-to-connect-to/</link><pubDate>Fri, 20 Dec 2013 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2013/12/20/dynagen-dynamips-error-netio_desc-create-udp-unable-to-connect-to/</guid><description>OS: CentOS 6.5 x86_64 installed on vmware Dynamips 0.2.10 There is an error when loading a .net file named as test.net with 100 devices in Dynagen.0.11.0:
netio_desc_create_udp: unable to connect to I searched on the Internet about this error msg, most of posts shared a method: specified UDP port of dynamips instance in .net file. But it doesn’t work for me.
As I found a Dynagen description in GNS3 website: however Dynagen is still updated and developed for GNS3, this means you can download GNS3 sources, find Dynagen in it.</description></item><item><title>Trouble shooting: Cisco router DHCP No option 125</title><link>https://blog.gainskills.top/2013/11/13/trouble-shooting-cisco-router-dhcp-no-option125/</link><pubDate>Wed, 13 Nov 2013 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2013/11/13/trouble-shooting-cisco-router-dhcp-no-option125/</guid><description>Topology:
Topo Configure DHCP on Cisco router 2811 to assign a static IP to the italkBB: Cisco SPA 1202.
start DHCP service by command:
service dhcp debug on Cisco router to check DHCP request by the commands:
debug ip dhcp server packet terminal monitor Debug info :
DHCPD: DHCPREQUEST received from client 0100.1c23.3541.98 configure DHCP
ip dhcp pool ItalkBB host 10.</description></item><item><title>make error :/usr/bin/ld: cannot find -luuid</title><link>https://blog.gainskills.top/2013/11/05/make-error-usrbinld-cannot-find-luuid/</link><pubDate>Tue, 05 Nov 2013 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2013/11/05/make-error-usrbinld-cannot-find-luuid/</guid><description>I met a make error in CentOS 6:
# make ...... /usr/bin/ld: cannot find -luuid ld returned 1 exit status make: *** Error 1 The way to fix this error is to install lib : uuid-devel
yum -y install libuuid-devel</description></item></channel></rss>